name: 🎯 Build and deploy apps to server

on:
  push:
    branches: [ main ]
    paths:
      - internal/
      - cmd/

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd backend
            git stash
            echo "Start pulling from github repository...."
            git pull origin main
            echo "Start build golang executable file...."
            export PATH=$PATH:/usr/local/go/bin
            go build -o main cmd/app/main.go
            echo "Restart service..."
            systemctl restart prelife.service